name: Run Xircuits Workflows Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      TEST_XIRCUITS: |
        examples/example.xircuits
        # path/to/your/workflow.xircuits
        # Add more .xircuits files as needed, one per line

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install xircuits
      run: pip install xircuits

    - name: List xircuits
      run: xircuits list

    - name: Set COMPONENT_LIBRARY_PATH
      run: |
        REPO_NAME="${GITHUB_REPOSITORY##*/}"
        COMPONENT_LIBRARY_PATH=$(echo "xai_components/xai_${REPO_NAME}" | sed 's/-/_/g')
        echo "COMPONENT_LIBRARY_PATH=$COMPONENT_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Clone Pull Request
      run: |
        PR_BRANCH=${{ github.event.pull_request.head.ref }}
        git clone -b $PR_BRANCH https://github.com/${{ github.repository }} ${{ env.COMPONENT_LIBRARY_PATH }}

    - name: Test .xircuits Workflows
      run: |
        export PYTHONPATH="${GITHUB_WORKSPACE}:${PYTHONPATH}"
        LOG_FILE="${GITHUB_WORKSPACE}/workflow_logs.txt"
        IFS=$'\n' read -r -a TEST_FILES <<< "$TEST_XIRCUITS"
        FAIL=0
        if [ ${#TEST_FILES[@]} -eq 0 ]; then
          echo "No .xircuits files specified for testing." | tee -a $LOG_FILE
        else
          for file in "${TEST_FILES[@]}"; do
            FULL_PATH="${COMPONENT_LIBRARY_PATH}/${file}"
            if [ -f "$FULL_PATH" ]; then
              WORKFLOW_LOG_FILE="${FULL_PATH%.*}_workflow_log.txt"
              echo "Processing $FULL_PATH..." | tee -a $LOG_FILE
              xircuits compile $FULL_PATH "${FULL_PATH%.*}.py" 2>&1 | tee -a $LOG_FILE
              python "${FULL_PATH%.*}.py" 2>&1 | tee -a $WORKFLOW_LOG_FILE
              LAST_LINE=$(tail -n 1 "$WORKFLOW_LOG_FILE")
              if [[ "$LAST_LINE" != "Finished Executing" ]]; then
                echo "Error: Workflow $FULL_PATH did not finish as expected" | tee -a $LOG_FILE
                FAIL=1
              else
                echo "$FULL_PATH processed successfully" | tee -a $LOG_FILE
              fi
              cat "$WORKFLOW_LOG_FILE" | tee -a $LOG_FILE
            else
              echo "Specified file $FULL_PATH does not exist" | tee -a $LOG_FILE
              FAIL=1
            fi
          done
        fi
        if [ $FAIL -ne 0 ]; then
          echo "One or more workflows failed or did not finish as expected." | tee -a $LOG_FILE
          exit 1
        else 
          echo "Workflow processing completed" | tee -a $LOG_FILE
        fi

    - name: Upload log file
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: workflow-logs
        path: ${{ github.workspace }}/workflow_logs.txt
